// LIST_SERVICES

export const LIST_SERVICES_ATTEMPT = 'LIST_SERVICES_ATTEMPT';
export const LIST_SERVICES_SUCCESS = 'LIST_SERVICES_SUCCESS';
export const LIST_SERVICES_FAILED = 'LIST_SERVICES_FAILED';
